import Foundation

@main struct VADTests {
    static func main() {
        var vad = VAD(endpointMS: 450, prerollMS: 200, minSpeechMS: 100, thresholdDB: -45)
        assert(vad.process(db: -60, durationMS: 100) == .none)
        assert(vad.process(db: -30, durationMS: 50) == .none)
        assert(vad.process(db: -60, durationMS: 50) == .none, "short noise must not start")
        assert(vad.process(db: -30, durationMS: 50) == .none)
        assert(vad.process(db: -30, durationMS: 50) == .start(prerollMS: 200))
        assert(vad.process(db: -60, durationMS: 400) == .none)
        assert(vad.process(db: -30, durationMS: 50) == .none, "brief gap does not end a word")
        assert(vad.process(db: -60, durationMS: 400) == .none)
        assert(vad.process(db: -60, durationMS: 50) == .end)
        assert(vad.process(db: -60, durationMS: 450) == .none)
        assert(vad.process(db: -30, durationMS: 100) == .start(prerollMS: 200), "returns to listening")
        vad.reset()
        assert(vad.process(db: -30, durationMS: 50) == .none)
        var fast = VAD(endpointMS: 80, prerollMS: 40, minSpeechMS: 20, thresholdDB: -20)
        assert(fast.process(db: -30, durationMS: 50) == .none, "threshold configurable")
        assert(fast.process(db: -10, durationMS: 20) == .start(prerollMS: 40))
        assert(fast.process(db: -60, durationMS: 80) == .end)
        var window = Preroll<Int>(capacityMS: 300)
        window.append(1, durationMS: 100)
        window.append(2, durationMS: 100)
        window.append(3, durationMS: 100)
        window.append(4, durationMS: 100)
        assert(window.values == [2, 3, 4], "old audio is discarded, recent pre-roll preserved")
        window.append(5, durationMS: 50)
        window.append(6, durationMS: 50)
        assert(window.values == [3, 4, 5, 6], "keeps 200 ms before 100 ms confirmation")
        window.clear()
        assert(window.values.isEmpty && window.durationMS == 0, "clears between phrases")
        var completed = SpeechProgress()
        completed.receive("Привет", isFinal: true)
        assert(!completed.needsContinuation(db: -60, thresholdDB: -45), "silence must not restart a completed Speech request")
        assert(completed.claimFinal() == "Привет", "completed phrase survives silence endpoint")
        assert(completed.claimFinal() == nil, "one final only")
        var continued = SpeechProgress()
        continued.receive("Привет", isFinal: true)
        assert(continued.needsContinuation(db: -30, thresholdDB: -45))
        continued.beginContinuation()
        continued.receive("мир", isFinal: false)
        assert(continued.claimFinal() == nil, "partial continuation is not a final")
        continued.receive("мир", isFinal: true)
        assert(continued.claimFinal() == "Привет мир", "continued voice joins same utterance with prefix")
        assert(continued.claimFinal() == nil)
        var failed = SpeechProgress()
        failed.receive("Привет", isFinal: true)
        failed.beginContinuation()
        failed.receive("ошибка", isFinal: false)
        assert(failed.restoreCompletedPrefix())
        assert(failed.claimFinal() == "Привет", "failed continuation never loses completed prefix or commits unfinished partial")
        var noiseRecovery = RecognitionRecoveryPolicy()
        var noiseVAD = VAD()
        for _ in 0..<3 {
            assert(noiseVAD.process(db: -30, durationMS: 100) == .start(prerollMS: 200))
            assert(!noiseRecovery.failure(domain: "kAFAssistantErrorDomain", code: 1110, available: true), "no-speech noise burst must keep listening")
            noiseVAD.reset()
        }
        assert(noiseRecovery.consecutiveFailures == 0, "no-speech does not consume service retries")
        assert(noiseVAD.process(db: -30, durationMS: 100) == .start(prerollMS: 200))
        var afterNoise = SpeechProgress()
        afterNoise.receive("Да", isFinal: true)
        assert(noiseVAD.process(db: -60, durationMS: 450) == .end)
        assert(afterNoise.claimFinal() == "Да", "phrase after noise succeeds")
        noiseRecovery.finalized()
        var serviceRecovery = RecognitionRecoveryPolicy()
        assert(!serviceRecovery.failure(domain: "kAFAssistantErrorDomain", code: 1101, available: true))
        assert(!serviceRecovery.failure(domain: "kAFAssistantErrorDomain", code: 1107, available: true))
        assert(serviceRecovery.failure(domain: "kAFAssistantErrorDomain", code: 1101, available: true), "real service failures remain bounded")
        serviceRecovery.finalized()
        assert(serviceRecovery.consecutiveFailures == 0)
        assert(!serviceRecovery.failure(domain: "other", code: 1110, available: true), "same code in another domain is a real failure")
        assert(serviceRecovery.consecutiveFailures == 1)
        assert(serviceRecovery.failure(domain: "kAFAssistantErrorDomain", code: 1110, available: false), "unavailable recognizer stops even after noise")
        print("VAD, preroll, Speech progress and recognition recovery assertions passed")
    }
}
